// <auto-generated />
namespace VSA_GameHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newmig8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmig8));
        
        string IMigrationMetadata.Id
        {
            get { return "202007200215565_newmig8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
